# Generated by Django 3.1.7 on 2021-03-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='percent',
            field=models.FloatField(default=0.0),
        ),
    ]
